version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - userid=${USER_ID}
        - groupid=${GROUP_ID}
    restart: unless-stopped
    ports:
      - "${PUBLIC_PORT}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    depends_on:
      - redis
      - mariadb
    networks:
      - mariadb-network
      - redis-network

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - ${ADMIN_PUBLIC_PORT}:8080
    depends_on:
      - mariadb
    networks:
      - mariadb-network

  mariadb:
    image: mariadb:10.11.2
    volumes:
      - .docker/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mariadb-network

  redis:
    image: redis:6.0.16
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - redis-network

networks:
  mariadb-network:
    driver: bridge
  redis-network:
    driver: bridge