version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - userid=${USER_ID}
        - groupid=${GROUP_ID}
    restart: unless-stopped
    ports:
      - "${PUBLIC_PORT}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
      - .docker/config/php8.1/php.ini-development:/etc/php81/php.ini
      - .docker/config/supervisor/supervisor.d:/etc/supervisor.d/