version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - userid=${USER_ID}
        - groupid=${GROUP_ID}
    restart: unless-stopped
    ports:
      - "${PUBLIC_PORT}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app